config/routes.rb
Wolf::Application.routes.draw do
  resources :advertisements

  resources :girls

  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/wolfadmin', :as => 'rails_admin'

  root 'girls#index'

end

app/models/advertisement.rb
# == Schema Information
#
# Table name: advertisements
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  sub_title  :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Advertisement < ActiveRecord::Base
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!
  
  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = Advertisement.all
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
  end

  # GET /advertisements/1/edit
  def edit
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @advertisement }
      else
        format.html { render action: 'new' }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:title, :sub_title, :content)
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/_form.html.erb
<%= form_for(@advertisement) do |f| %>
  <% if @advertisement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertisement.errors.count, "error") %> prohibited this advertisement from being saved:</h2>

      <ul>
      <% @advertisement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sub_title %><br>
    <%= f.text_field :sub_title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertisements/_info.html.erb
<% if advertisement %>
  <h1><span class="label label-danger"><%= advertisement.title %></span></h1>
  <p class="lead"><%= advertisement.sub_title %></p>
  <% if advertisement.content.strip.start_with?("h") %>
    <%= link_to("详情请点击查看", advertisement.content, class: "btn btn-lg btn-success") %>
  <% else %>
    <%= link_to("详情请点击查看", advertisement, class: "btn btn-lg btn-success") %>
  <% end %>
  <hr>
<% end %>

app/views/advertisements/edit.html.erb
<h1>Editing advertisement</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertisement %> |
<%= link_to 'Back', advertisements_path %>

app/views/advertisements/index.html.erb
<h1>Listing advertisements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Sub title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>
        <td><%= advertisement.title %></td>
        <td><%= advertisement.sub_title %></td>
        <td><%= advertisement.content %></td>
        <td><%= link_to 'Show', advertisement %></td>
        <td><%= link_to 'Edit', edit_advertisement_path(advertisement) %></td>
        <td><%= link_to 'Destroy', advertisement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertisement', new_advertisement_path %>

app/views/advertisements/new.html.erb
<h1>New advertisement</h1>

<%= render 'form' %>

<%= link_to 'Back', advertisements_path %>

app/views/advertisements/show.html.erb
<p id="notice"><%= notice %></p>

 <h1><span class="label label-danger"><%= @advertisement.title %></span></h1>
 <h3 class = "text-info"><%= @advertisement.sub_title %></h2>

<p class="lead"><%= raw @advertisement.content %></p>


<%= link_to '返回列表', girls_path, class: "btn btn-lg btn-primary" %>