config/routes.rb
Wolf::Application.routes.draw do
  resources :advertisements

  resources :girls

  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/wolfadmin', :as => 'rails_admin'

  root 'girls#index'

end

app/models/girl.rb
# == Schema Information
#
# Table name: girls
#
#  id         :integer          not null, primary key
#  qq         :string(255)
#  city       :string(255)
#  height     :integer
#  weight     :integer
#  grade_id   :integer
#  age_min    :integer
#  age_max    :integer
#  height_min :integer
#  height_max :integer
#  weight_min :integer
#  weight_max :integer
#  comment    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  birth      :date
#

class Girl < ActiveRecord::Base
  belongs_to :grade
  default_scope { order('id DESC') }

  self.per_page = 10

  attr_accessor :fit_error

  rails_admin do 
    edit do
      field :qq
      field :city
      field :height
      field :weight
      field :birth
      field :grade
      field :age_min
      field :age_max
      field :height_min
      field :height_max
      field :weight_min
      field :weight_max
      field :comment
    end

    list do
      field :qq
      field :city
      field :height
      field :weight
      field :birth
      field :comment
      field :grade
      field :age_min
      field :age_max
      field :height_min
      field :height_max
      field :weight_min
      field :weight_max
    end

    show do
      field :qq
      field :city
      field :height
      field :weight
      field :birth
      field :comment
      field :grade
      field :age_min
      field :age_max
      field :height_min
      field :height_max
      field :weight_min
      field :weight_max
    end
  end

  def self.avaliables
    indexs = []
    Grade.all.each do |grade|
      indexs << grade.id if grade.to_s == "member" or grade.to_s == "vip"
    end
    where(grade_id: indexs)
  end

  def fit current_user
    user = current_user
    self.fit_error = ""
    user_grade = user.grade.to_s
    girl_grade = self.grade.to_s
    if user_grade == "member" && girl_grade == "vip"
      self.fit_error = "申请失败：此信息仅限VIP成员申请"
      return false
    end

    if user_grade == "none"
      self.fit_error = "申请失败：此信息仅限VIP成员申请"
      return false
    end

    # validate the province
    city_valid = false
    user_citys = user.city.to_s.split("；")
    user_citys.each do |city|
      if city[0..1] == self.city.to_s[0..1]
        city_valid = true
        break
      end
    end
    unless city_valid
      self.fit_error = "申请失败：不在同一省份不允许申请，VIP成员请向管理员申请外省肉"
      return false
    end
    
    if !(user.age >= self.age_min and user.age <= self.age_max \
      and user.height >= self.height_min and user.height <= self.height_max \
      and user.weight >= self.weight_min and user.weight <= self.weight_max)
      self.fit_error = "申请失败：您不符合对方的要求"
      return false
    end

    return true
  end

  def age
    self.birth.nil? ? 0 : Time.now.year - self.birth.year
  end

  def info
    "#{self.city} #{self.age}岁 #{self.height}cm #{self.weight}kg"
  end

  def demand
    "要求男生年龄#{self.age_min}~#{self.age_max}岁 身高:#{self.height_min}~#{self.height_max}cm 体重:#{self.weight_min}~#{self.weight_max}kg"
  end
end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
  before_action :set_girl, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /girls
  # GET /girls.json
  def index
    @girls = Girl.avaliables.page(params[:page])
    @advertisements = Advertisement.all
  end

  # GET /girls/1
  # GET /girls/1.json
  def show
    @girl.fit current_user
    @advertisement = Advertisement.last
  end

  # GET /girls/new
  def new
    @girl = Girl.new
  end

  # GET /girls/1/edit
  def edit
  end

  # POST /girls
  # POST /girls.json
  def create
    @girl = Girl.new(girl_params)

    respond_to do |format|
      if @girl.save
        format.html { redirect_to @girl, notice: 'Girl was successfully created.' }
        format.json { render action: 'show', status: :created, location: @girl }
      else
        format.html { render action: 'new' }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /girls/1
  # PATCH/PUT /girls/1.json
  def update
    respond_to do |format|
      if @girl.update(girl_params)
        format.html { redirect_to @girl, notice: 'Girl was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /girls/1
  # DELETE /girls/1.json
  def destroy
    @girl.destroy
    respond_to do |format|
      format.html { redirect_to girls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_girl
      @girl = Girl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def girl_params
      params.require(:girl).permit(:qq, :city, :birth, :height, :weight, :grade_id, :age_min, :age_max, :height_min, :height_max, :weight_min, :weight_max, :comment)
    end
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/views/girls/_form.html.erb
<%= form_for(@girl) do |f| %>
  <% if @girl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@girl.errors.count, "error") %> prohibited this girl from being saved:</h2>

      <ul>
      <% @girl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :qq %><br>
    <%= f.text_field :qq %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :grade_id %><br>
    <%= f.number_field :grade_id %>
  </div>
  <div class="field">
    <%= f.label :age_min %><br>
    <%= f.number_field :age_min %>
  </div>
  <div class="field">
    <%= f.label :age_max %><br>
    <%= f.number_field :age_max %>
  </div>
  <div class="field">
    <%= f.label :height_min %><br>
    <%= f.number_field :height_min %>
  </div>
  <div class="field">
    <%= f.label :height_max %><br>
    <%= f.number_field :height_max %>
  </div>
  <div class="field">
    <%= f.label :weight_min %><br>
    <%= f.number_field :weight_min %>
  </div>
  <div class="field">
    <%= f.label :weight_max %><br>
    <%= f.number_field :weight_max %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/girls/edit.html.erb
<h1>Editing girl</h1>

<%= render 'form' %>

<%= link_to 'Show', @girl %> |
<%= link_to 'Back', girls_path %>

app/views/girls/index.html.erb
<div>
  <% @girls.each_with_index do |girl, index| %>
    <h1 class="text-success"><%= girl.info %></h1>
    <%= link_to "申请", girl_path(girl), class: "btn btn-lg btn-primary" %>
    <p class="lead"><%= girl.demand %><br><%= girl.comment %></p>
    <hr>
    <% if (index % 3 == 2) %>
      <%= render partial: 'advertisements/info', locals: { advertisement: @advertisements[1- index%2] }   if @advertisements[1- index%2] %>
    <% end %>
  <% end %>
</div>

<div class="apple_pagination">
    <%= will_paginate @posts %>
</div>

app/views/girls/new.html.erb
<h1>New girl</h1>

<%= render 'form' %>

<%= link_to 'Back', girls_path %>

app/views/girls/show.html.erb
<p id="notice"><%= notice %></p>

<% if @girl.fit_error.size > 0 %>
  <h1><span class="label label-danger"><%= @girl.fit_error %></span></h1>
<% else %>
  <h1><span class="label label-success">恭喜您申请成功</span></h1>
  <h1>QQ号:<%= @girl.qq %></h1>
<% end %>

<hr>

<%= link_to '返回列表', girls_path, class: "btn btn-lg btn-primary" %>

<hr>
<%= render partial: 'advertisements/info', locals: { advertisement: @advertisement } %>